config/routes.rb
Rails.application.routes.draw do
  get 'albums/index'

  get 'albums/show'

  resources :artists, only: [:index, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id          :integer          not null, primary key
#  name        :string
#  image_url   :string
#  released_at :datetime
#  artist_id   :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Album < ApplicationRecord
  belongs_to :artist
  has_many :songs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id         :integer          not null, primary key
#  name       :string
#  image_url  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Artist < ApplicationRecord
  has_many :albums
end

app/models/song.rb
# == Schema Information
#
# Table name: songs
#
#  id          :integer          not null, primary key
#  name        :string
#  number      :integer
#  preview_url :string
#  album_id    :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Song < ApplicationRecord
  belongs_to :album
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all
  end

  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])

    @albums = @artist.albums  

  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/albums/index.html.erb
<h1>Albums#index</h1>
<p>Find me in app/views/albums/index.html.erb</p>

app/views/albums/show.html.erb
<h1>Albums#show</h1>
<p>Find me in app/views/albums/show.html.erb</p>

app/views/artists/index.html.erb
<div class="row">
  <% @artists.each do |artist| %>
    <div class="col-xs-3">
      <div class="panel panel-default">
        <div class="panel-body">
          <%= image_tag(artist.image_url, class:'img-responsive') unless artist.image_url.blank? %>
        
          <h3 class="text-center"><%= artist.name.capitalize %></h3>
          <button class="center-block btn btn-default btn-block"><%= link_to 'Ver más', artist_path(artist) %></button> 
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/artists/show.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="page-header">
      <h2><%= @artist.name.capitalize %> <small>Albums (<%= @albums.count %>)</small></h2>
    </div>
  </div>
  
  <div class="col-xs-12 col-md-4 visible-xs visible-sm margin-bottom">
    <%= image_tag(@artist.image_url, class:'img-responsive') unless @artist.image_url.blank? %>
  </div>

  <div class="col-xs-12 col-md-8">
    <div class="row">
      
        <% @albums.each do |album| %>
          <div class="col-xs-6 col-md-3">
            <div class="panel panel-default">
              <div class="panel-body">
                <%= image_tag(album.image_url, class:'img-responsive') unless album.image_url.blank? %>
              
                <h6><%= album.name %></h6>
                <p><%= album.released_at %></p>
            
              </div>
            </div>
          </div>
        <% end %>
      
    </div>
    
  </div>
  <div class="col-xs-12 col-md-4 hidden-xs hidden-sm">
    <%= image_tag(@artist.image_url, class:'img-responsive') unless @artist.image_url.blank? %>
  </div>

</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <a class="navbar-brand" href="#">
        <span class="logo glyphicon glyphicon-headphones" aria-hidden="true"></span>
      </a>
    
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Artistas', artists_path %></li>
        <li><a href="#">Mi música</a></li>
      </ul>
    
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Mi cuenta <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="https://www.makeitreal.camp" target="_blank">Make it Real</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpotLite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/nav' %>

    <div class="container">
      <%= yield %>
    </div>  
  </body>
</html>